### ISSUE TITLE
Wrong date in JSON-STAT 1.0 output

### ISSUE THREAD

**Issue by likp** [statisticssweden/PxWeb#104]
**Describe the bug**
When fetching a table in JSON-STAT 1.0 the updated attribute in JSON is wrong. Insted of when the table was last updated one receives the creation time of the table.  

**To Reproduce**
Just select any table and any variables and values and go the presentation page. Then download the file as JSON-STAT 1.

**Expected behavior**
The creation date

**Actual behavior**
The last updated date

**Environment information**
All PxWeb versions

**Additional context**
problem is in the following line of code
https://github.com/statisticssweden/PCAxis.Serializers.JsonStat/blob/d525164b869be3c4b0387c1ceabe903b053e5d93/PCAxis.Serializers.JsonStat/JsonStatSerializer.cs#L117

**Comment by trygu** [comment]
https://github.com/statisticssweden/PCAxis.Serializers.JsonStat/pull/2

**Comment by likp** [comment]
This has been fixed altough we have to manually rebuild the nugets for PCAxis.Serializers.JsonStat

**Comment by snudekat** [comment]
Hi, in Slovenia we have another request about this field in JSON (or any other) output file. I'm not sure whether it's ok to add it to this discussion or add a new one? The issue is that PX files have two kind of metadata - one is file information and the other is PX metadata. So when any output (including JSON) is created, the "last updated" field should be neither file creation date nor "CREATION_DATE" metadata field in the PC-Axis file, but "LAST_UPDATED" value as written in the metadata part of the file. At least that's how we understand the file metadata structure - we use "CREATION_DATE" as the date when the matrix was first published in the database and doesn't reflect last updated date at all, I hope the others use it the same way?

**Comment by trygu** [comment]
Riiight.. This is where I'm on thin ice I think; There is a difference in how PX files and CNMM handles these different date fields. And I think there is also a difference depending on the number of Contents you have as well. The reason I used this field many years ago is that it's unambiguous, and I didn't want to wade into a complex logic around these date fields. But it might be simple enough using the same logic that's already in place. What do you think @likp?

**Comment by likp** [comment]
As long is I have been working with PX-file we have always used the keyword CREATION-DATE to store the date when the PX-file was created that is that each time you save it it will get a new date. This might be wrong but no one as complaint about this yet. 
LAST-UPDATED stores the date when the data in the PX file as updated. If you have multiple contents then you have a LAST-UPDATED for each content. I

**Comment by Hansseman** [comment]
I think we agree that the LAST_UPDATED is the date the table was last updated/published?

Why is the CREATION_DATE of the table so important for Slovenia. 
We have aso belived that the CREATION_DATE is the first creation date of the timeseries table.
The FIRST-PUBLISHED would solve this problem?

Still there is the file datestamp used by px-file based PxWeb. This is weird!
I think it should allways use the information from within the Px-file. Or am i wrong?

**Comment by snudekat** [comment]
Hello Hans,
for us CREATION_DATE is not really important, we just don't understand why it's used as "last updated". I sincerely believe the PX metadata within the LAST_UPDATED field should be used instead. The same field is also shown in PX-Web as the last updated info. But we never use cont-variable specifics dates...
