### ISSUE TITLE
Problem with building Master branch

### ISSUE THREAD

**Issue by mcsugaman** [statisticssweden/PxWeb#31]
Hi,

I wuold like to build this project, but I get a bunch of errors.

It seems, that a core of the problems are Strong Name Key.pfx files, which are missing and solution is unable to build. How can I face this issue?

Thanks.

**Comment by likp** [comment]
Hi @mcsugaman and sorry for the late reply,

Yes it is the key that we use to sign the official assemblies. You could genererat a key of your own an place it i n all the locations that are missing it. You also have to replace the PublicKeyToken to the assemblies in CommandBarPlugins.xml, CommandBarPluginsOperations.xml, CommandBarPluginsViews.xml, FileConfig.xml and other locations where we assemblies are referenced. Or you could just change all the projects so that they are not signed.

An alternative could be to look at the netstandard branch where we are actively working and where we have removed the signing.

**Comment by likp** [comment]
@mcsugaman I will close the issue and I hope the previous answers solved your problems.
